default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000
  username: cal
  password: 

test:
  <<: *default
  database: i

development:
  <<: *default
  database: i


production:
  <<: *default
  database: i


