default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: root
  password: 

development:
  <<: *default
  database: ihubstartups


production:
  <<: *default
  database: ihubstartups


